select * from customer limit 20;


-- 1. what is the total amount of revenue generated by male vs female customers?

SELECT gender , SUM(purchase_amount) as revenue
from customer
group by gender;

-- 2. which customers used a discount but still spent more than the average purchase amount? 

SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);

-- 3. Which are the top 5 products with the highest average review rating?

SELECT  item_purchased , ROUND(AVG(review_rating::numeric),2) as Top_5_products
from customer
group by item_purchased
order by Top_5_products desc limit 5;

-- 4. compare the average purchase amounts between standard and express shipping.

SELECT shipping_type , ROUND(AVG(purchase_amount),2) as average_purchase
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--5. Do subscribed customer spend more? compare average spend and total revenue between subscribers and non- subscribers.

SELECT subscription_status , COUNT(customer_id),ROUND(AVG(purchase_amount),2) as average_spend , ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by average_spend , total_revenue desc;

--6. which 5 products have the highest percertage of purchases with discounts applied ?

SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
group by item_purchased
order by discount_rate desc
limit 5;

--7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

with customer_type as (
select customer_id,previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
FROM customer
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

--8. What are the top 3 most purchased products within each category?

with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category order by count(customer_id) DESC ) AS item_rank
from customer
group by category,item_purchased
)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <= 3;

--9. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

--10. What is the revenue contribution of each age group ? 

select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group 
order by total_revenue desc;